kill_list = [
    "was killed by Lord Rama in Ramayana.",
    "tried to swim in lava.",
    "was pricked to death.",
    "experienced Kinetic Energy. Probably didn't learn Physics properly.",
    "blew up!",
    "drowned in the sink.",
    "was blown up by TNT.",
    "was killed by [Intentional Game Design].",
    "hit the ground too hard.",
    "fell from a high place.",
    "fell off a ladder.",
    "was impaled on a stalagmite.",
    "was squashed by a falling anvil.",
    "was squashed by a falling block.",
    "was skewered by a falling stalactite.",
    "went up in flames.",
    "burned to death.",
    "walked into fire whilst fighting 'INEVITABLE death'.",
    "was burnt to a crisp whilst fighting Thanos. Sad that the kiddo thought he had a chance to beat him.",
    "went off with a BANG! #SayNoToCrackers",
    "was struck by lightning.",
    "discovered the floor was lava.",
    "was killed by magic.",
    "froze to death.",
    "was stung to death.",
    "was obliterated by a sonically-charged shriek.",
    "starved to death.",
    "suffocated in a wall.",
    "was squished too much.",
    "was squashed by pet toy.",
    "was poked to death by a sweet berry bush.",
    "fell out of the world.",
    "didn't want to live in the same world as death.",
    "withered away.",
    "died from dehydration.",
    "was roasted in dragon breath.",
    "was doomed to fall.",
    "was too soft for this world.",
    "blasted",
    "died from too much caffiene",
    "ate mentos after drinking coke",
    "died from depression",
    "committed suicide",
    "was blood drained",
    "'s skull was smashed",
    "was killed by a creeper",
    "Slipped on ice, never to rise again.",
    "Tangled with a venomous serpent.",
    "Succumbed to a cursed artifact's power.",
    "Overestimated their swimming prowess.",
    "Faced a lethal dose of potion misfortune.",
    "Trespassed in a dragon's lair, never to return.",
    "Danced with death in a haunted mansion.",
    "Fell prey to quicksand's silent embrace.",
    "Discovered nature's wrath in a forgotten jungle.",
    "Succumbed to a dragon's fiery breath.",
    "Defied prophecy, met destiny's sting.",
    "Tried juggling torches, ended up toast.",
    "Stared down a basilisk, blinked first... forever.",
    "Danced under anvils, got a crushing finale.",
    "Played hide and seek with a ghost, found a permanent spot.",
    "Challenged a snail to a race, lost in slo-mo.",
    "Fought a ninja chicken, got egg on their face.",
    "Slipped on a banana peel, slipped into eternity.",
    "Thought they could fly, met a harsh reality.",
    "Wrestled a vacuum, got sucked into defeat.",
    "Tried to out-dance a gorgon, got stoned.",
    "Challenged a mime to silence, lost their voice.",
    "Befriended a grumpy cat, got scratched out.",
    "Trained bees, got stung out.",
    "Negotiated with a toaster, got burnt.",
    "Argued with a lawyer bot, got lawyered.",
    "was kissed into oblivion"
    "didn't deserve to live"]