prac = [
    "Tate amar baal chhera gelo.",
    "Eta kirokom crossover?!",
    "Sorry bhai.",
    "Alada Nirman",
    "Tor baba",
    "Life e jokhoni nijer opor doubt hobe, okhane haat debe.",
    "The hell is a semi-friend? You are friend with like the bottom half or something?",
    "Dara paayer mora shukno chamra ta ghose aaschi.",
    "Otake dialogue bole na. Dialogue dujoner majhkhane hoy…ar tor saathe keu kotha bole na.",
    "Toke dekhe ekta 9-to-5 dudh cha addict government worker mone hoy.",
    "ebhabe kepe kepe morbe shob kota",
    "LESSFYAKINGO",
    "did you jonkle your balls",
    "Kutte ho kya",
    "May he get jonkled in his balls",
    "Bandor sala schizo bole diye chole gelo",
    "pede felbi I think",
    "Cibil emginir",
    "things have to return to equilibrium kaku",
    "until your retarded ass informed me about this",
    "his diabetic ass cant piss 🗣️ 🗣️ 🗣️",
    "fucktard fell into a corner behind bookshelf",
    "bari te jama kaporer auditing cholche naki",
    "appel bedana narkel",
    "tora laddoo gulo claim kor hotobhaga",
    "Say Gex HK 4DR",
    "I get impatient on waning gibbous moons",
    "3 month later dekha gelo I moved to austria studying art",
    "MANGO MANGO MANGO",
    "Well trace amounts of gu prottek food e thake",
    "Yuri aache?",
    "Ghuma you slob of fatty tissue",
    "I chopped off my fingers cooking this with 420L of oliveoil and 69 stockpot, it was my choice",
    "Dupur bela suor ta khele more jetam",
    "night khujte keno hobe already aache toh",
    "Those whose rectums have been raptured, we are setting up rehabilitation centres",
    "turns out I write full blown cinematic games ghum e",
    "mfw profanity filter on in dreams",
    "puffy word ta eto cute keno",
    "passion ta ki paanu",
    "mfw 3 + 4 is a 1x1 matrix",
    "tui erom apod lokjon (ourselves included) life e paash kikore shobsomoy",
    "testicular tear",
    "good meat/fat ratio",
    "haagle aaro 2 kg kome jaabe",
    "Jonmodin er din shobai erom Malay-Bahasa Indonesia bole keno",
    "Stardew Valley kinbo bhabchi. Green Onion sprite ta khub homely dekhte",
    "toke circumcise korte aashbe raatre",
    "Tor jibon e hothat hothat kore leora dhuke jaay keno",
    "Tui eta likhe ki prapto korli jibon e",
    "I have the urge to eat Fondant, Mushroom Sauce ar Wasabi",
    "For inciting riots, sedition, sexual harassment, homosexuality, bestiality, sodomy, racial violence, discrimination of race, discrimination of gender, discrimination of caste, casteism, xenophobia, maoist tendencies, etc er jonno tui kobe dhora porbi?",
    "stupid word ta dekhlei r/arkham mone hoy",
    "abaar gaal kheye gelo shuknolonka ta",
    "i remembered amaar test tube e copper jome geche",
    "karor kaache industrial acid aache?",
    "Ill offer 5\% \\equity",
    "whale er jerom blowhole, serom shithole"
]